/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#b80049',
        secondary: '#5f00e3',
        background: '#fcf9f8',
        surface: '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'on-background': '#1c1b1b',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#5b3f43',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#400014',
        'on-primary-fixed-variant': '#900038',
        'primary-fixed': '#ffd9de',
        'primary-fixed-dim': '#ffb2be',
        'primary-container': '#e2165f',
        'inverse-primary': '#ffb2be',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#eee4ff',
        'on-secondary-fixed': '#22005d',
        'on-secondary-fixed-variant': '#5400cc',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#cfbcff',
        'secondary-container': '#7836ff',
        'tertiary': '#625966',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7c717f',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ecdeee',
        'tertiary-fixed-dim': '#cfc2d2',
        'on-tertiary-fixed': '#201924',
        'on-tertiary-fixed-variant': '#4d4450',
        'outline': '#8f6f73',
        'outline-variant': '#e4bdc2',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'surface-tint': '#bc004b',
      },
      spacing: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        base: '4px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      fontSize: {
        'headline-sm': ['20px', { fontWeight: '600', lineHeight: '1.3' }],
        'headline-md': ['24px', { fontWeight: '600', lineHeight: '1.3' }],
        'body-lg': ['16px', { fontWeight: '400', lineHeight: '1.5' }],
        'body-md': ['14px', { fontWeight: '400', lineHeight: '1.5' }],
        'label-sm': ['12px', { fontWeight: '500', lineHeight: '1.4' }],
        'label-lg': ['14px', { fontWeight: '600', lineHeight: '1.4' }],
        'display-lg': ['32px', { fontWeight: '700', letterSpacing: '-0.02em', lineHeight: '1.2' }],
        'display-lg-mobile': ['28px', { fontWeight: '700', lineHeight: '1.2' }],
      },
      fontFamily: {
        'headline-sm': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'display-lg-mobile': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
